# Autogenerated wrapper script for Qiskit_jll for aarch64-linux-musl
export libqiskit

using Python_jll
JLLWrappers.@generate_wrapper_header("Qiskit")
JLLWrappers.@declare_library_product(libqiskit, "libqiskit.so")
function __init__()
    JLLWrappers.@generate_init_header(Python_jll)
    JLLWrappers.@init_library_product(
        libqiskit,
        "lib/libqiskit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
