# Autogenerated wrapper script for Qiskit_jll for aarch64-apple-darwin
export libqiskit

using Python_jll
JLLWrappers.@generate_wrapper_header("Qiskit")
JLLWrappers.@declare_library_product(libqiskit, "@rpath/libqiskit_cext.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Python_jll)
    JLLWrappers.@init_library_product(
        libqiskit,
        "lib/libqiskit.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
